/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiReferenceIndexRouteImport } from './routes/api-reference/index'
import { Route as ApiReferenceSplatRouteImport } from './routes/api-reference/$'
import { Route as ApiReferenceHealthRouteImport } from './routes/api-reference/health'
import { Route as CookbookIndexRouteImport } from './routes/cookbook/index'
import { Route as CookbookSlugRouteImport } from './routes/cookbook/$slug'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as PlaygroundIndexRouteImport } from './routes/playground/index'
import { Route as ShowcaseIndexRouteImport } from './routes/showcase/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceIndexRoute = ApiReferenceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiReferenceRoute,
} as any)
const ApiReferenceSplatRoute = ApiReferenceSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiReferenceRoute,
} as any)
const ApiReferenceHealthRoute = ApiReferenceHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => ApiReferenceRoute,
} as any)
const CookbookIndexRoute = CookbookIndexRouteImport.update({
  id: '/cookbook/',
  path: '/cookbook/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbookSlugRoute = CookbookSlugRouteImport.update({
  id: '/cookbook/$slug',
  path: '/cookbook/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseIndexRoute = ShowcaseIndexRouteImport.update({
  id: '/showcase/',
  path: '/showcase/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api-reference/$': typeof ApiReferenceSplatRoute
  '/api-reference/health': typeof ApiReferenceHealthRoute
  '/cookbook/$slug': typeof CookbookSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/api-reference/': typeof ApiReferenceIndexRoute
  '/cookbook/': typeof CookbookIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/showcase/': typeof ShowcaseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api-reference/$': typeof ApiReferenceSplatRoute
  '/api-reference/health': typeof ApiReferenceHealthRoute
  '/cookbook/$slug': typeof CookbookSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/api-reference': typeof ApiReferenceIndexRoute
  '/cookbook': typeof CookbookIndexRoute
  '/docs': typeof DocsIndexRoute
  '/playground': typeof PlaygroundIndexRoute
  '/showcase': typeof ShowcaseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api-reference/$': typeof ApiReferenceSplatRoute
  '/api-reference/health': typeof ApiReferenceHealthRoute
  '/cookbook/$slug': typeof CookbookSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/api-reference/': typeof ApiReferenceIndexRoute
  '/cookbook/': typeof CookbookIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/showcase/': typeof ShowcaseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-reference'
    | '/docs'
    | '/manifest.webmanifest'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api-reference/$'
    | '/api-reference/health'
    | '/cookbook/$slug'
    | '/docs/$'
    | '/api-reference/'
    | '/cookbook/'
    | '/docs/'
    | '/playground/'
    | '/showcase/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manifest.webmanifest'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api-reference/$'
    | '/api-reference/health'
    | '/cookbook/$slug'
    | '/docs/$'
    | '/api-reference'
    | '/cookbook'
    | '/docs'
    | '/playground'
    | '/showcase'
  id:
    | '__root__'
    | '/'
    | '/api-reference'
    | '/docs'
    | '/manifest.webmanifest'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api-reference/$'
    | '/api-reference/health'
    | '/cookbook/$slug'
    | '/docs/$'
    | '/api-reference/'
    | '/cookbook/'
    | '/docs/'
    | '/playground/'
    | '/showcase/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiReferenceRoute: typeof ApiReferenceRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CookbookSlugRoute: typeof CookbookSlugRoute
  CookbookIndexRoute: typeof CookbookIndexRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
  ShowcaseIndexRoute: typeof ShowcaseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference/': {
      id: '/api-reference/'
      path: '/'
      fullPath: '/api-reference/'
      preLoaderRoute: typeof ApiReferenceIndexRouteImport
      parentRoute: typeof ApiReferenceRoute
    }
    '/api-reference/$': {
      id: '/api-reference/$'
      path: '/$'
      fullPath: '/api-reference/$'
      preLoaderRoute: typeof ApiReferenceSplatRouteImport
      parentRoute: typeof ApiReferenceRoute
    }
    '/api-reference/health': {
      id: '/api-reference/health'
      path: '/health'
      fullPath: '/api-reference/health'
      preLoaderRoute: typeof ApiReferenceHealthRouteImport
      parentRoute: typeof ApiReferenceRoute
    }
    '/cookbook/': {
      id: '/cookbook/'
      path: '/cookbook'
      fullPath: '/cookbook/'
      preLoaderRoute: typeof CookbookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbook/$slug': {
      id: '/cookbook/$slug'
      path: '/cookbook/$slug'
      fullPath: '/cookbook/$slug'
      preLoaderRoute: typeof CookbookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/playground/': {
      id: '/playground/'
      path: '/playground'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/': {
      id: '/showcase/'
      path: '/showcase'
      fullPath: '/showcase/'
      preLoaderRoute: typeof ShowcaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiReferenceRouteChildren {
  ApiReferenceSplatRoute: typeof ApiReferenceSplatRoute
  ApiReferenceHealthRoute: typeof ApiReferenceHealthRoute
  ApiReferenceIndexRoute: typeof ApiReferenceIndexRoute
}

const ApiReferenceRouteChildren: ApiReferenceRouteChildren = {
  ApiReferenceSplatRoute: ApiReferenceSplatRoute,
  ApiReferenceHealthRoute: ApiReferenceHealthRoute,
  ApiReferenceIndexRoute: ApiReferenceIndexRoute,
}

const ApiReferenceRouteWithChildren = ApiReferenceRoute._addFileChildren(
  ApiReferenceRouteChildren,
)

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiReferenceRoute: ApiReferenceRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CookbookSlugRoute: CookbookSlugRoute,
  CookbookIndexRoute: CookbookIndexRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
  ShowcaseIndexRoute: ShowcaseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
