import { CubeIcon } from '@phosphor-icons/react';
import { createFileRoute } from '@tanstack/react-router';

export const Route = createFileRoute('/showcase/')({
  component: ShowcasePage,
});

const SHOWCASE_SLIDES = [
  { desc: 'Dark theme cover with ambient accent glows, metric pills, and speaker notes.', id: 1, title: 'Slide 1: Executive Cover Slide & Shadow Accents' },
  { desc: 'Vector shapes, auto-shapes, geometry palettes, and custom coordinates.', id: 2, title: 'Slide 2: Modular Architecture & Shape Geometry Gallery' },
  { desc: 'Multi-column tables with custom headers, alternating rows, and cell padding.', id: 3, title: 'Slide 3: Multi-Style Enterprise Data Tables' },
  { desc: 'Branded units (Inches, Points, Degrees, EMU) and unit conversion tables.', id: 4, title: 'Slide 4: Type-Safe Units & Formula Matrix' },
  { desc: 'Microservice floating cards with coordinate transformations and z-indexing.', id: 5, title: 'Slide 5: Decoupled Microservice Architecture Cards' },
  { desc: 'PNG, JPEG, and SVG images with aspect ratio scaling and placeholder replacements.', id: 6, title: 'Slide 6: High-Fidelity Image Embedding & Media Gallery' },
  { desc: 'Hierarchical bullets (levels 0 to 8) with custom symbols and inline modifiers.', id: 7, title: 'Slide 7: Multilevel Hierarchical Bullet Matrix' },
  { desc: 'Shape attachments via top, bottom, left, and right sites with arrowheads.', id: 8, title: 'Slide 8: Connectors & Process Flow Pipelines' },
  { desc: 'Native DrawingML Bar, Column, Line, and Area charts with custom colors.', id: 9, title: 'Slide 9: OpenXML Native Charts & Visual Analytics' },
  { desc: 'Side-by-side comparative charts with legends and data markers.', id: 10, title: 'Slide 10: Multi-Topology Chart Gallery' },
  { desc: 'Spiderweb radar charts, pie distributions, and stacked area charts.', id: 11, title: 'Slide 11: Specialized Topologies (Area, Pie, Radar)' },
  { desc: 'Internal slide jumps, external web URLs, and slide show action buttons.', id: 12, title: 'Slide 12: Interactive Hyperlinks & Slide Controls' },
  { desc: 'Multi-stop color gradients with custom angles and opacity values.', id: 13, title: 'Slide 13: DrawingML Linear & Radial Gradient Engine' },
  { desc: 'Sub-millisecond latency profile and bundle footprint comparisons.', id: 14, title: 'Slide 14: Engine Benchmark Matrix' },
];

/**
 * Visual showcase gallery page component.
 * @returns React node
 */
function ShowcasePage() {
  return (
    <div className="w-full max-w-[1600px] mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="text-center max-w-2xl mx-auto mb-12">
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-rose-500/10 text-rose-400 text-xs font-semibold mb-3 border border-rose-500/20">
          <CubeIcon className="h-3.5 w-3.5" />
          14-Slide Comprehensive Suite
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-foreground">
          Visual Showcase Gallery
        </h1>
        <p className="mt-3 text-sm text-muted-foreground">
          The complete 14-slide showcase deck generated by @hokkyss/pptx. Run `pnpm demo` in the workspace root to generate this deck locally.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {SHOWCASE_SLIDES.map((slide) => (
          <div className="p-6 rounded-2xl bg-card text-card-foreground border border-border hover:border-primary/40 transition flex flex-col justify-between shadow-sm" key={slide.id}>
            <div>
              <div className="flex items-center justify-between">
                <span className="text-xs font-mono text-primary bg-primary/10 px-2 py-0.5 rounded border border-primary/20">
                  Slide
                  {' '}
                  {slide.id}
                  {' '}
                  of 14
                </span>
                <span className="text-xs text-muted-foreground">16:9 Widescreen</span>
              </div>
              <h3 className="text-lg font-bold text-card-foreground mt-3">{slide.title}</h3>
              <p className="text-xs text-muted-foreground mt-2">{slide.desc}</p>
            </div>

            <div className="mt-4 pt-4 border-t border-border/30 text-xs font-mono text-muted-foreground flex justify-between items-center">
              <span>pnpm demo:showcase</span>
              <span className="text-emerald-400">ECMA-376 Valid</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
